name: scharts_flutter_core
description: Charts Flutter Core is a dependent package for all the Charts Flutter widgets. 
version: 18.3.40+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ">=2.1.0 <=3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
